# Generated by Django 5.1.6 on 2025-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
