# Generated by Django 5.1.6 on 2025-02-21 19:17

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_homepage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bg_image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', validators=[blog.models.validate_image_dimension]),
        ),
    ]
