# Generated by Django 5.1.6 on 2025-02-25 19:10

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', validators=[blog.models.validate_image_dimension]),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='Sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', validators=[blog.models.validate_image_dimension]),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='Sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', validators=[blog.models.validate_image_dimension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='Sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
